version: "3.3"
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    volumes:
      - ./nginxlog:/var/log/nginx
    ports:
      - "8888:80"
    links:
      - php
    
  php:
    build:
      context: ./php-cli
    container_name: php
    ports:
      - "80:80"