version: "3.3"
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    volumes:
      #- ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginxlog:/var/log/nginx
    ports:
      - "8888:80"
    links:
      - php
    
  php:
    build:
      context: ./php-cli
    container_name: php
    #volumes:
    #  - ./index.php:/var/www/index.php
    ports:
      - "80:80"