version: "3.3"
services:
  nginx_pub:
    build:
      context: ./nginx
    container_name: nginx_public
    volumes:
      #- ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginxlog:/var/log/nginx
    ports:
      - "8888:80"
    
  php_local:
    build:
      context: ./php-cli
    container_name: php_local
    #volumes:
    #  - ./index.php:/var/www/index.php
    ports:
      - 80:80