version: '3.8'
services:
  nginx_pub:
    image: nginx:latest
    container_name: nginx_public
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./nginx.access.log:/var/log/nginx/access.log
    ports:
      - 8888:80
    links:
      - php_local
    
  php_local:
    build: 
      dockerfile: dockerfile
    container_name: php_local
    volumes:
      - ./index.php:/var/www/index.php
    #ports:
    #  - 80:80